FROM golang:1.16 as debug

# installing git
# RUN apk update && apk upgrade && \
#     apk add --no-cache git \
#         dpkg \
#         gcc \
#         git \
#         musl-dev

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
ENV GOPROXY "https://goproxy.cn"

WORKDIR /go/src/work
COPY ./src /go/src/work/
RUN pwd
RUN go build -o app
RUN go get github.com/go-delve/delve/cmd/dlv
### Run the Delve debugger ###
COPY ./dlv.sh /
RUN chmod +x /dlv.sh 
ENTRYPOINT [ "/dlv.sh"]

###########START NEW IMAGE###################

FROM alpine:3.9 as prod
COPY --from=debug /go/src/work/app /
CMD ./app
